[[block]]
block = "focused_window"
max_width = 15
show_marks = "visible"

[[block]]
block = "net"
device = "eth0"
format = "{speed_down;K*b} {graph_down;}"
interval = 5
[block.theme_overrides]
idle_fg = "#00b8ff"

[[block]]
block = "memory"
format_mem = "({mem_used_percents})"
display_type = "memory"
clickable = true
interval = 5
[block.theme_overrides]
idle_fg = "#001eff"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"
interval = 5
[block.theme_overrides]
idle_fg = "#001eff"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total}"
[block.theme_overrides]
critical_fg = "#d600ff"

[[block]]
block = "sound"
format = "{volume}"
[block.theme_overrides]
idle_fg = "#d600ff"

[[block]]
block = "custom"
command = "acpi -V | grep % | head -1 | tail -c 5"
interval = 60
[block.theme_overrides]
idle_fg = "#ff0000"

[[block]]
block = "custom"
command = "date | head -c 23"
interval = 1
[block.theme_overrides]
idle_fg = "#ff0000"
